# Generated by Django 2.1.8 on 2020-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(max_length=32, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='detail',
            field=models.CharField(max_length=32, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=32, verbose_name='工具名'),
        ),
    ]
