# Generated by Django 2.1.8 on 2020-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPlatform', '0002_auto_20200320_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(max_length=512, verbose_name='描述'),
        ),
    ]
