# Generated by Django 2.1.8 on 2019-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LableDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(auto_created=True)),
                ('table_name', models.CharField(max_length=128)),
                ('fund_account', models.CharField(max_length=16)),
                ('value', models.CharField(max_length=512)),
                ('value_type', models.IntegerField()),
                ('interval_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LableNum',
            fields=[
                ('table_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('table_num', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
