# Generated by Django 2.1.8 on 2019-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20191031_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='labledetail',
            name='column_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='labledetail',
            name='interval_type',
            field=models.CharField(max_length=4),
        ),
    ]
