# Generated by Django 2.1.8 on 2019-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20191031_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labledetail',
            name='fund_account',
        ),
        migrations.RemoveField(
            model_name='labledetail',
            name='value',
        ),
        migrations.RemoveField(
            model_name='labledetail',
            name='value_type',
        ),
        migrations.AddField(
            model_name='labledetail',
            name='fund_account_max',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='labledetail',
            name='fund_account_min',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='labledetail',
            name='max_value',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='labledetail',
            name='min_value',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='labledetail',
            name='null_value',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='labledetail',
            name='interval_type',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='labledetail',
            name='table_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
