# Generated by Django 2.1.8 on 2019-12-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20191107_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16)),
                ('summary', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
