# Generated by Django 2.1.8 on 2019-12-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='url',
            field=models.CharField(default='', max_length=64),
        ),
    ]
