# Generated by Django 2.1.8 on 2020-03-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_tools_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=16)),
                ('port', models.IntegerField()),
                ('user', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
