# Generated by Django 2.1.8 on 2020-03-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20200311_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('section', models.CharField(default='', max_length=32)),
                ('option', models.CharField(default='', max_length=32)),
                ('value', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
