# Generated by Django 2.1.8 on 2020-03-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='ConfigTable',
        ),
    ]
