# Generated by Django 2.1.8 on 2020-03-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20200326_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtable',
            name='section_flag',
            field=models.BooleanField(default=0),
        ),
    ]
