# Generated by Django 2.1.8 on 2020-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_configtable_section_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtable',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
