# Generated by Django 2.1.8 on 2020-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_auto_20200327_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtable',
            name='version',
            field=models.CharField(default='', max_length=128),
        ),
    ]
